### ISSUE TITLE
Config gets made in projects assets but its stuck on make config file.

### ISSUE THREAD

**Issue by Toys0125** [kaaori/DynamicBonesStudio#1]
So, I put the master in the project assets open the window for the studio click the button but doesn't go away and a dynamicbonespresets.txt gets made in the editor folder of the master folder for the studio.

**Comment by Toys0125** [comment]
Changing line 103 from the one before to just /DynamicBonesStudio-master... got it to work.

**Comment by kaaori** [comment]
Should be fixed in most recent version! Sorry about that!
