### ISSUE TITLE
Only works in specific folder else stuck on make config file

### ISSUE THREAD

**Issue by OneVoltTen** [kaaori/DynamicBonesStudio#2]
`void OnEnable() {
    _cfgFilePath = Application.dataPath + "/Kaori/DynamicBonesStudio/Editor/DynamicBonesPresets.txt";
}`
This logic requires the specific folder path else it doesn't work. Should either state this in the readme or improve the code.

**Comment by kaaori** [comment]
Hey! Most recent commit should fix this.

Instead of using a static path (not sure why I did in the first place, sorry!) it now grabs the directory of the editor window and creates the config file there.

Thank you for the feedback!
